// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-grpc/internal/api"
	"go-grpc/internal/base"
	"go-grpc/internal/biz"
	"go-grpc/internal/data/article"
	"go-grpc/internal/server"
)

// Injectors from wire.go:

func NewApp() (*App, func(), error) {
	conf := base.NewConf()
	blogDB := base.NewBlogDB(conf)
	iArticleDao := article.NewArticleDao(blogDB)
	iArticleBiz := biz.NewArticleBiz(iArticleDao)
	iCommentBiz := biz.NewCommentBizBiz()
	iUserBiz := biz.NewUserBiz()
	logger := base.NewLogger()
	apiApi := api.NewApi(iArticleBiz, iCommentBiz, iUserBiz, logger)
	iServerGrpc := server.NewGRPCServer(apiApi, conf)
	iServerHttp := server.NewHttpServer(apiApi, conf)
	app := &App{
		Grpc: iServerGrpc,
		Http: iServerHttp,
	}
	return app, func() {
	}, nil
}
